### ISSUE TITLE
Different `t` for data in a minibatch

### ISSUE THREAD

**Issue by ain-soph** [google-research/torchsde#129]
In `torchdiffeq` ODE repo https://github.com/rtqichen/torchdiffeq/issues/122#issuecomment-738978844, there is a dummy-variable trick that could enable users to use different `t` for different inputs in the same minibatch. I wonder if we can do the same thing on SDE equation. If so, could anyone kindly provide the formula of modified `f` and `g`?

`dx = f(x,t)dt + g(x,t)dw`

I'm currently solving SDE equation with a ts tuple `(t_start, t_end)`

-------------------------------------
For ODE `dx=f(x,t)dt`,
I could make a variable replacement `t=(t_end - t_start)*s+t_start` to transform different `t` range into the same `s` range in `(0, 1)`.  
And `new_f(x, s) = dx/ds = dx/dt * dt/ds = f(x, t(s)) * (t_end - t_start)`

I greedily remind everyone that I see in this repo. Hope that won't disturb.
@lxuechen @patrick-kidger @mtsokol

**Comment by patrick-kidger** [comment]
For batch-dependent times, probably the simplest thing to do is to use [Diffrax](https://github.com/patrick-kidger/diffrax) instead, in conjunction with `jax.vmap`.

**Comment by ain-soph** [comment]
> For batch-dependent times, probably the simplest thing to do is to use [Diffrax](https://github.com/patrick-kidger/diffrax) instead, in conjunction with `jax.vmap`.

@patrick-kidger Thanks for your quick reply. That seems a perfect solution in JAX. Sadly all my codes are written in PyTorch. Is there anything that I could use in `functorch`? They have `vmap` as well.

**Comment by patrick-kidger** [comment]
You could try `torch.vmap`, but I believe it's untested with torchsde. (Or torchdiffeq.)

If you want to reparameterise then you can use the [self-similarity of scaling](https://en.wikipedia.org/wiki/Wiener_process#Brownian_scaling) property for Brownian motion. Note that this scales as `sqrt(c)` (rather than just `c` as in the ODE case).

That said, I've done this before, and it can behave a bit weirdly. It generally means you need to have your output times be a union over the whole batch, and then do a gather -- this is exceptionally slow. In addition torchsde's adaptive solvers handle the whole batch in one go, so if two different batch elements have very different scales then you might find more steps are taken than are really necessary.

(This exact use case was one of the things I was really looking to fix when I wrote Diffrax.)

**Comment by ain-soph** [comment]
@patrick-kidger Thanks for your advice! You are absolutely right!
`dx = f(x,t)dt+g(x,t)dw(t)`
I use the formula `dw(t)=sqrt(dt)*ϵ(t, t+dt)=sqrt(dt/ds) * dw(s)` and it becomes
`dx = f(x,t) * dt/ds * ds + g(x,t) * sqrt(dt/ds) * dw(s)`

I apply this in my code and it works fine.  
But just as you said, it becomes much slower. I guess it's because of the variable range increase.  
(e.g., original `t` ranges in `[0.3, 0.5]`, but now `s` range becomes `[0, 1]`. In the meantime, the step size is not changed, so it calculates much more steps.)
I'll try to unify them in range `[0, precision]` where `precision` is a mutable argument. I'll see if that works.

After all, thanks for your generous work!

**Comment by ain-soph** [comment]
Yes, After making precision the same as original `t` scale, the execution speed using `s` is the same as using raw `t`.
