### ISSUE TITLE
Question about the "increment of Brownian motion" 

### ISSUE THREAD

**Issue by abdulfatir** [google-research/torchsde#93]
Can someone explain what exactly does the parameter `W` (The increment of the Brownian motion over the interval [t0, t1]) in `BrownianInterval` mean mathematically? 

Let's say that I have a Brownian motion with `E[dB_t dB_t^T] = Qdt`. Is the parameter `W` related to `Q`? If yes, how should I set the value of `W` given that I have `Q`?

**Comment by patrick-kidger** [comment]
The parameter `W` is equal to `B_{t_1} - B_{t_0}`. For example it can be set to zero, so that `BrownianInterval` samples from a Brownian bridge.

In particular that should mean that it is unrelated to your use case. I believe sampling uncorrelated Brownian motion (via `BrownianInterval`) and then multiplying by `sqrt(Q)` should give you the distribution you're after.

**Comment by abdulfatir** [comment]
Thanks a lot for the clarification, @patrick-kidger.

A small follow-up:

Setting the diffusion function (`g`) equal to `cholesky(Q)`/`sqrt(Q)` in the SDE should produce the same effect, right? Assume that my `state_dim` and `brownian_dim` are equal and the SDE that I am interested in looks something like this:

```
dy(t) = f(t, y(t)) dt + dW(t)  with       y(t0) = y0    and    E[dW(t)dW(t)^T] = Qdt
```

**Comment by patrick-kidger** [comment]
Yep, that sounds correct to me.

**Comment by abdulfatir** [comment]
Awesome, thanks! Closing this.
